# Generated by Django 4.1.5 on 2023-02-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlisting_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='created',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='listedBy',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='modified',
        ),
    ]
