# Generated by Django 4.1.5 on 2023-02-24 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auctionlisting_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='listedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
