# Generated by Django 4.1.5 on 2023-02-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auctionlisting_listedby_auctionlisting_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
