# Generated by Django 4.1.5 on 2023-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_auctionlisting_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='modified',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
