# Generated by Django 4.1.5 on 2023-02-24 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_auctionlisting_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
