# Generated by Django 4.1.5 on 2023-02-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auctionlisting_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
