# Generated by Django 4.1.5 on 2023-02-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_auctionlisting_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='startingBid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
