# Generated by Django 4.1.5 on 2023-02-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auctionlisting_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='startingBid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='currentBid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bid', to='auctions.bids'),
        ),
    ]
