# Generated by Django 4.1.5 on 2023-02-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_remove_auctionlisting_currentbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.FloatField(),
        ),
    ]
