# Generated by Django 4.1.5 on 2023-02-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_alter_auctionlisting_startingbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='startingBid',
        ),
    ]
