# Generated by Django 4.1.5 on 2023-03-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_remove_auctionlisting_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.FloatField(unique=True),
        ),
    ]
