# Generated by Django 4.1.5 on 2023-03-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logComment', to='auctions.comment'),
        ),
    ]
